package uk.ac.bris.cs.rfideasalreadytaken.lumberjack;

public enum ScanReturn {
    SUCCESSRETURN,
    SUCCESSREMOVAL,
    SUCCESSRETURNANDREMOVAL,
    SUCCESSUSERLOADED,
    SUCCESSSCANREMOVE,
    FAILUSERNOTRECOGNISED,
    FAILUSERGROUPRULESETNOTCOMPATABLE,
    FAILDEVICENOTRECOGNISED,
    FAILUSERATDEVICELIMIT ,
    FAILUSERNORPERMITTEDTOREMOVE ,
    FAILDEVICEUNAVIALABLE ,
    ERRORCONNECTIONFAILED ,
    ERRORUSERNOTLOADED ,
    ERRORDEVICENOTLOADED,
    ERRORDEVICEHANDLINGFAILED,
    ERRORRETURNFAILED ,
    ERRORREMOVALFAILED
}
